# Generated by Django 2.2.6 on 2019-10-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(verbose_name='Название статьи')),
                ('text', models.TextField(max_length=10000, verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор комментария')),
                ('text', models.CharField(max_length=500, verbose_name='Текст комментария')),
                ('like', models.PositiveSmallIntegerField(verbose_name='Лайки')),
            ],
        ),
    ]
